var express = require('express');
var router = express.Router();
var bodyParser = require('body-parser');
var oracledb = require('oracledb');

var mrouter = require("./mrouter");

var connAttrs = {
    "user": "IDMA_SELECT",
    "password": "HappyNewYear2017",
    "connectString": "10.171.128.46:51521/IDMET3AB.tsystems.com"
}

var thisArg = {
  router: router,
  oracledb: oracledb,
  connAttrs: connAttrs
};

mrouter(thisArg, "/", "SELECT 'ACCOUNT' AS TBL, A.* FROM IDMA_BESTANDS_OPDB_DATA.X_ACCOUNT A WHERE  rownum <= 10")
//mrouter.call(thisArg, "/:GUID", "SELECT 'ACCOUNT' AS TBL, A.* FROM IDMA_BESTANDS_OPDB_DATA.X_ACCOUNT A WHERE A.GUID=:GUID", "GUID")
mrouter(thisArg, "/:GUID/XHisAuftrag", "SELECT  'X_HIS_AUFTRAG' AS TBL, XH.*  \
FROM IDMA_AUFTRAGS_OPDB_DATA.X_ACCOUNT_INFO AI \
INNER JOIN IDMA_BESTANDS_OPDB_DATA.X_ACCOUNT A ON A.TO_NR=AI.TO_NR \
INNER JOIN IDMA_AUFTRAGS_DISPDB_DATA.X_HIS_AUFTRAG XH ON AI.O_ID=XH.EO_ID \
WHERE A.GUID=:GUID \
ORDER BY XH.TS_LAST_UPDATE ", "GUID")

mrouter(thisArg, "/:GUID/XAuftrag", "SELECT  'X_AUFTRAG' AS TBL, AU.*  \
FROM IDMA_AUFTRAGS_OPDB_DATA.X_ACCOUNT_INFO AI \
INNER JOIN IDMA_BESTANDS_OPDB_DATA.X_ACCOUNT A ON A.TO_NR=AI.TO_NR \
INNER JOIN IDMA_AUFTRAGS_OPDB_DATA.X_AUFTRAG AU ON AI.O_ID=AU.EO_ID \
WHERE A.GUID=:GUID \
ORDER BY AU.TS_LAST_UPDATE ", "GUID")

mrouter(thisArg, "/:GUID/XAuftragExt", "SELECT  'X_AUFTRAG_EXT ' AS TBL, AX.*  \
FROM IDMA_AUFTRAGS_OPDB_DATA.X_ACCOUNT_INFO AI \
INNER JOIN IDMA_BESTANDS_OPDB_DATA.X_ACCOUNT A ON A.TO_NR=AI.TO_NR \
INNER JOIN IDMA_AUFTRAGS_OPDB_DATA.X_AUFTRAG_EXT AX ON AI.O_ID=AX.EO_ID \
WHERE A.GUID=:GUID \
ORDER BY AX.LAST_UPD ", "GUID")

mrouter(thisArg, "/:GUID/XAuftragExt2Sof", "SELECT  'X_AUFTRAG_EXT_2_SOF' AS TBL, A2S.*  \
FROM IDMA_AUFTRAGS_OPDB_DATA.X_ACCOUNT_INFO AI \
INNER JOIN IDMA_BESTANDS_OPDB_DATA.X_ACCOUNT A ON A.TO_NR=AI.TO_NR \
INNER JOIN IDMA_AUFTRAGS_OPDB_DATA.X_AUFTRAG_EXT_2_SOF A2S ON AI.O_ID=A2S.EO_ID \
WHERE A.GUID=:GUID \
ORDER BY A2S.LAST_UPD ", "GUID")

mrouter(thisArg, "/:GUID/XMessage", "SELECT  'X_MESSAGES' AS TBL, XM.*  \
FROM IDMA_AUFTRAGS_OPDB_DATA.X_ACCOUNT_INFO AI \
INNER JOIN IDMA_BESTANDS_OPDB_DATA.X_ACCOUNT A ON A.TO_NR=AI.TO_NR \
INNER JOIN IDMA_AUFTRAGS_DISPDB_DATA.X_MESSAGES XM ON AI.O_ID=XM.EO_ID \
WHERE A.GUID=:GUID \
ORDER BY XM.ID ", "GUID")

mrouter(thisArg, "/:GUID/XError", "SELECT  'X_ERROR' AS TBL, XE.*  \
FROM IDMA_AUFTRAGS_OPDB_DATA.X_ACCOUNT_INFO AI \
INNER JOIN IDMA_BESTANDS_OPDB_DATA.X_ACCOUNT A ON A.TO_NR=AI.TO_NR \
INNER JOIN IDMA_AUFTRAGS_OPDB_DATA.X_ERROR XE ON AI.O_ID=XE.EO_ID \
WHERE A.GUID=:GUID \
ORDER BY XE.LAST_UPD", "GUID")


module.exports = router;