var express = require('express');
var router = express.Router();
var bodyParser = require('body-parser');
var oracledb = require('oracledb');

var mrouter = require("../router");

var connAttrs = {
    "user": "IDMA_SELECT",
    "password": "HappyNewYear2017",
    "connectString": "10.171.128.46:51521/IDMET3AB.tsystems.com"
}

var thisArg = {
    router: router,
    oracledb: oracledb,
    connAttrs: connAttrs
};

mrouter.call(thisArg, "/", "SELECT \
XA.SO_TYPE_ID, XA.STATUS \
,SOF.SPECIAL_ORDER_FLAG_ID, SOF.NAME \
,XE.ID,XE.EO_ID, XE.SO_ID, XE.CODE_INT, XE.CODE_EXT, XE.SYS, XE.TASK, XE.TEXT_INT, XE.TEXT_EXT, XE.INC_TEXT_SHORT, XE.INC_TEXT_LONG, XE.HANDLING \
FROM IDMA_AUFTRAGS_OPDB_DATA.X_ERROR XE \
LEFT JOIN IDMA_AUFTRAGS_OPDB_DATA.X_AUFTRAG XA ON XE.SO_ID=XA.SO_ID \
LEFT JOIN IDMA_AUFTRAGS_OPDB_DATA.X_AUFTRAG_EXT_2_SOF XAE2S ON XAE2S.EO_ID=XA.EO_ID \
LEFT JOIN IDMA_AUFTRAGS_OPDB_DATA.SPECIAL_ORDER_FLAG SOF ON SOF.SPECIAL_ORDER_FLAG_ID=XAE2S.SPECIAL_ORDER_FLAG_ID \
WHERE 1=1 \
AND  rownum <= 10 \
ORDER BY XE.EO_ID \
")


mrouter.call(thisArg, "/:GUID/GUID", "SELECT \
XAC.GUID, XAC.TO_NR \
,XE.EO_ID, XE.SO_ID, XE.CODE_INT, XE.CODE_EXT, XE.SYS, XE.TASK, XE.TEXT_INT, XE.TEXT_EXT, XE.INC_TEXT_SHORT, XE.INC_TEXT_LONG, XE.HANDLING \
FROM IDMA_BESTANDS_OPDB_DATA.X_ACCOUNT XAC \
JOIN IDMA_AUFTRAGS_OPDB_DATA.X_ACCOUNT_INFO XAI ON XAI.TO_NR=XAC.TO_NR \
JOIN IDMA_AUFTRAGS_OPDB_DATA.X_AUFTRAG_EXT XAE ON XAI.O_ID=XAE.EO_ID \
LEFT JOIN IDMA_AUFTRAGS_OPDB_DATA.X_ERROR XE ON XE.EO_ID=XAE.EO_ID \
WHERE 1=1 \
AND  XAC.GUID=:GUID \
", "GUID")

mrouter.call(thisArg, "/:ID/ID", "SELECT \
XE.ID, XE.EO_ID, XE.SO_ID, XE.CODE_INT, XE.CODE_EXT, XE.SYS, XE.TASK, XE.TEXT_INT, XE.TEXT_EXT, XE.INC_TEXT_SHORT, XE.INC_TEXT_LONG, XE.HANDLING \
FROM  IDMA_AUFTRAGS_OPDB_DATA.X_ERROR XE \
WHERE 1=1 \
AND  XE.ID=:ID \
", "ID")

module.exports = router;